config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :memos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord

  validates :title, :content, presence: :true
  validates :title, length: { maximum: 140 }
  validates :content, length: { maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  def index
    @memos = Memo.all
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    if @memo.save
      redirect_to memos_path
    else
      render :new
    end
  end

  def show
    @memo = Memo.find(params[:id])
  end

  def edit
    # @memo = Memo.find(params[:id])
  end

  def update
    if @memo.update(memo_params)
      redirect_to memos_path
    else
      render
    end
  end

  def destroy
    # memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to "/memos"
  end

  private

  def memo_params
    params.require(:memo).permit(:title, :content)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<% if blog.errors.any? %>
  <% blog.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_for blog do |f| %>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <%= f.submit %>
<% end %>

app/views/memos/edit.html.erb
<h1>メモ編集画面</h1>

<%= form_for @memo, url: "/memos/#{@memo.id}", html: { method: :patch } do |f| %>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>

  <%= f.submit %>
<% end %>

app/views/memos/index.html.erb
<%= link_to "メモ新規作成", "/memos/new" %>

<input class="form-control" id="search_word" type="text" placeholder="メモタイトル">

<table class="table table-striped">
  <thead class="bg-danger text-white">
    <tr>
      <th>タイトル</th>
    </tr>
  </thead>

  <tbody id="search_table">
    <% @memos.each do |memo| %>
    <tr>
      <td><%= memo.title %></td>
      <td>
      <%= link_to "詳細", memo_path(memo), class: "btn btn-primary" %>
      <%= link_to "編集", edit_memo_path(memo), class: "btn btn-secondary" %>
      <%= link_to "削除", memo_path(memo), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function(){
    $("#search_word").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#search_table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/memos/new.html.erb
<h1>メモ投稿画面</h1>

<%= form_for @memo do |f| %>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>

  <%= f.submit %>
<% end %>

app/views/memos/show.html.erb
<h1>メモ詳細画面</h1>

<p><%= @memo.title %></p>
<p><%= @memo.content %></p>

<%= link_to "一覧画面に戻る", "/memos" %>